const createProductTypes = {
    PRODUCT_CREATE_START : 'PRODUCT_CREATE_START',
    PRODUCT_CREATE_SUCCESS : 'PRODUCT_CREATE_SUCCESS',
    PRODUCT_CREATE_ERROR : 'PRODUCT_CREATE_ERROR',

    PRODUCT_UPDATE_START : 'PRODUCT_UPDATE_START',
    PRODUCT_UPDATE_SUCCESS : 'PRODUCT_UPDATE_SUCCESS',
    PRODUCT_UPDATE_ERROR : 'PRODUCT_UPDATE_ERROR',
}

export default createProductTypes;