const cartTypes = {
    ADD_SUBLET_TO_CART : 'ADD_SUBLET_TO_CART',
    REMOVE_SUBLET_FROM_CART : 'REMOVE_SUBLET_FROM_CART',
    UPDATE_SUBLET_IN_CART : 'UPDATE_SUBLET_IN_CART',

    ORDER_START : 'ORDER_START',
    ORDER_SUCCESS : 'ORDER_SUCCESS',
    ORDER_ERROR : 'ORDER_ERROR',
}

export default cartTypes;