const categoryTypes = {
    ACTIVE_CATEGORY_START : 'ACTIVE_CATEGORY_START',
    ACTIVE_CATEGORY_SUCCESS : 'ACTIVE_CATEGORY_SUCCESS',
    ACTIVE_CATEGORY_ERROR : 'ACTIVE_CATEGORY_ERROR',
}

export default categoryTypes;