const sellerProductsTypes = {
    SELLER_PRODUCTS_START : 'SELLER_PRODUCTS_START',
    SELLER_PRODUCTS_SUCCESS : 'SELLER_PRODUCTS_SUCCESS',
    SELLER_PRODUCTS_ERROR : 'SELLER_PRODUCTS_ERROR',

    CHOOSE_DEPARTMENT : 'CHOOSE_DEPARTMENT',

    DEMOGRAPHICS_START : 'DEMOGRAPHICS_START',
    DEMOGRAPHICS_SUCCESS : 'DEMOGRAPHICS_SUCCESS',
    DEMOGRAPHICS_ERROR : 'DEMOGRAPHICS_ERROR',

    CHOOSE_DEMOGRAPHIC : 'CHOOSE_DEMOGRAPHIC',

    CATEGORIES_START : 'CATEGORIES_START',
    CATEGORIES_SUCCESS : 'CATEGORIES_SUCCESS',
    CATEGORIES_ERROR : 'CATEGORIES_ERROR',

    CHOOSE_CATEGORY : 'CHOOSE_CATEGORY',

    COMPANIES_START : 'COMPANIES_START',
    COMPANIES_SUCCESS : 'COMPANIES_SUCCESS',
    COMPANIES_ERROR : 'COMPANIES_ERROR',

    CHOOSE_COMPANY : 'CHOOSE_COMPANY',


}

export default sellerProductsTypes;