const orderTypes = {
    ALL_ORDERS_START : 'ALL_ORDERS_START',
    ALL_ORDERS_SUCCESS : 'ALL_ORDERS_SUCCESS',
    ALL_ORDERS_ERROR : 'ALL_ORDERS_ERROR',
    
    ORDER_DETAILS_START : 'ORDER_DETAILS_START',
    ORDER_DETAILS_SUCCESS : 'ORDER_DETAILS_SUCCESS',
    ORDER_DETAILS_ERROR : 'ORDER_DETAILS_ERROR',

}
 export default orderTypes;