const userTypes = {
    AUTH_TOKEN_START : 'AUTH_TOKEN_START',
    AUTH_TOKEN_SUCCESS : 'AUTH_TOKEN_SUCCESS',
    AUTH_TOKEN_ERROR : 'AUTH_TOKEN_ERROR',

    CUSTOMER_START : 'CUSTOMER_START',
    CUSTOMER_SUCCESS : 'CUSTOMER_SUCCESS',
    CUSTOMER_ERROR : 'CUSTOMER_ERROR',

    SELLER_START : 'SELLER_START',
    SELLER_SUCCESS : 'SELLER_SUCCESS',
    SELLER_ERROR : 'SELLER_ERROR',

    SELLER_UPDATE_START : 'SELLER_UPDATE_START',
    SELLER_UPDATE_SUCCESS : 'SELLER_UPDATE_SUCCESS',
    SELLER_UPDATE_ERROR : 'SELLER_UPDATE_ERROR',

    ADD_ADDRESS_START : 'ADD_ADDRESS_START',
    ADD_ADDRESS_SUCCESS : 'ADD_ADDRESS_SUCCESS',
    ADD_ADDRESS_ERROR : 'ADD_ADDRESS_ERROR',

    ADD_CONTACT_START : 'ADD_CONTACT_START',
    ADD_CONTACT_SUCCESS : 'ADD_CONTACT_SUCCESS',
    ADD_CONTACT_ERROR : 'ADD_CONTACT_ERROR',

    LOGOUT : 'LOGOUT',

}

export default userTypes;