const userTypes = {
    AUTH_TOKEN_START : 'AUTH_TOKEN_START',
    AUTH_TOKEN_SUCCESS : 'AUTH_TOKEN_SUCCESS',
    AUTH_TOKEN_ERROR : 'AUTH_TOKEN_ERROR',

    CUSTOMER_START : 'CUSTOMER_START',
    CUSTOMER_SUCCESS : 'CUSTOMER_SUCCESS',
    CUSTOMER_ERROR : 'CUSTOMER_ERROR',

    LOGOUT : 'LOGOUT',

}

export default userTypes;