const productTypes = {
    PRODUCT_START : 'PRODUCT_START',
    PRODUCT_SUCCESS : 'PRODUCT_SUCCESS',
    PRODUCT_ERROR : 'PRODUCT_ERROR',

    SELECT_SUBLET : 'SELECT_SUBLET',
    SELECT_IMAGE : 'SELECT_IMAGE',

    CHANGE_SEARCH_TEXT : 'CHANGE_SEARCH_TEXT',
    SEARCH_RESULTS_START : 'SEARCH_RESULTS_START',
    SEARCH_RESULTS_SUCCESS : 'SEARCH_RESULTS_SUCCESS',
    SEARCH_RESULTS_ERROR : 'SEARCH_RESULTS_ERROR',

    SUGGESTED_PRODUCTS_START : 'SUGGESTED_PRODUCTS_START',
    SUGGESTED_PRODUCTS_SUCCESS : 'SUGGESTED_PRODUCTS_SUCCESS',
    SUGGESTED_PRODUCTS_ERROR : 'SUGGESTED_PRODUCT_ERROR',

    ADD_REVIEW_START : 'ADD_REVIEW_START',
    ADD_REVIEW_SUCCESS : 'ADD_REVIEW_SUCCESS',
    ADD_REVIEW_ERROR : 'ADD_REVIEW_ERROR',

    SET_ACTIVE_OFFER : 'SET_ACTIVE_OFFER',
}

export default productTypes;