const departmentTypes = {
    ALL_DEPARTMENTS_START : 'ALL_DEPARTMENTS_START',
    ALL_DEPARTMENTS_SUCCESS : 'ALL_DEPARTMENTS_SUCCESS',
    ALL_DEPARTMENTS_ERROR : 'ALL_DEPARTMENTS_ERROR',

    ACTIVE_DEPARTMENT_START : 'ACTIVE_DEPARTMENT_START',
    ACTIVE_DEPARTMENT_SUCCESS : 'ACTIVE_DEPARTMENT_SUCCESS',
    ACTIVE_DEPARTMENT_ERROR : 'ACTIVE_DEPARTMENT_ERROR',
    
}

export default departmentTypes;